### ISSUE TITLE
对长文本进行解密时会被截断

### ISSUE THREAD

**Issue by dream2333** [fidcz/xxtea-python#1]

**Comment by fidcz** [comment]
长度多少会截断，我试试

**Comment by fidcz** [comment]
已修复

**Comment by dream2333** [comment]
可以用了，但实在是太慢了，不知道为何，用numba+jit nopython加速也还是很慢

**Comment by fidcz** [comment]
> 可以用了，但实在是太慢了，不知道为何，用numba+jit nopython加速也还是很慢

那可以试试 https://github.com/xxtea 这里的python版本，是直接调用c的

**Comment by dream2333** [comment]
> > 可以用了，但实在是太慢了，不知道为何，用numba+jit nopython加速也还是很慢
> 
> 那可以试试 https://github.com/xxtea 这里的python版本，是直接调用c的

这个的实现和js解密出来的不同
